version: 0.1
os: linux 
files:
  - source: my-app-1.0-SNAPSHOT.jar
    destination: /home/ubuntu/
  - source: app.yml
    destination: /home/ubuntu/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall: 
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh    
      timeout: 300
      runas: ubuntu